 **Prathmesh Dubey D11AD 16
Experiment 1**

**Explore Top-5 Data Analytics Libraries in Python (w.r.t Features & Applications)**

**1.NumPy**

*    NumPy is the fundamental package for scientific computing in Python. It
is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

**2. Pandas**


*   Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data.The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

**3. scikit-learn**


*   Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python. This library, which is largely written in Python, is built upon NumPy, SciPy and Matplotlib.

**4. SciPy**


*   The SciPy is an open-source scientific library of Python that is distributed under a BSD license. It is used to solve the complex scientific and mathematical problems. It is built on top of the Numpy extension, which means if we import the SciPy, there is no need to import Numpy. The SciPy library supports integration, gradient optimization, special functions, ordinary differential equation solvers, parallel programming tools, and many more.

**5. Tensorflow**

*   TensorFlow is an open-source machine learning library developed by Google. TensorFlow is used to build and train deep learning models as it facilitates the creation of computational graphs and efficient execution on various hardware platforms.TensorFlow is basically a software library for numerical computation using data flow graphs where:
*   nodes in the graph represent mathematical operations.
*   edges in the graph represent the multidimensional data arrays (called tensors) communicated between them.




**Install 2 Libraries for Python and perform simple experiments**

In [ ]:
import numpy as np
print("Code1:")
arr = np.array([3, 2, 1])
print("Array with Rank 1: \n",arr)

arr = np.array([[3, 2, 1],
                [5, 4, 6]])
print("Array with Rank 2: \n", arr)
print("\n")
print("Code2:")
array = np.array([[3, 2, 1],
                [5, 4, 6]])

print("Sorted Array")
print(np.sort(array, axis=None))
print("Sorted Array row wise")
print(np.sort(array, axis=1))
print("Sorted Array column wise")
print(np.sort(array, axis=0))
print("\n")
print("Code3:")
array = np.array([1,2,3,4,5,6,7,8,9])

reversed_array = np.flipud(array)
print(reversed_array)

Code1:
Array with Rank 1: 
 [3 2 1]
Array with Rank 2: 
 [[3 2 1]
 [5 4 6]]


Code2:
Sorted Array
[1 2 3 4 5 6]
Sorted Array row wise
[[1 2 3]
 [4 5 6]]
Sorted Array column wise
[[3 2 1]
 [5 4 6]]


Code3:
[9 8 7 6 5 4 3 2 1]


In [ ]:
import pandas as pd
from sklearn.datasets import load_wine

wine_data = load_wine()

wine_df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [ ]:
wine_df.tail()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     od280/od315_of_diluted_wines  proline  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0

In [ ]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [ ]:
import scipy
import tensorflow

**Explore Top-5 Data Analytics Libraries in R (w.r.t Features & Applications)**

**1. dplyr**
*  The dplyr is a powerful R-package to manipulate, clean and summarize unstructured data. In short, it makes data exploration and data manipulation easy and fast in R.The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data. Another most important advantage of this package is that it's very easy to learn and use dplyr functions.

**2. stringr**


* The stringr package provides a cohesive set of functions designed to make working with strings as easy as possible. stringr is built on top of stringi, which uses the ICU C library to provide fast, correct implementations of common string manipulations. stringr focusses on the most important and commonly used string manipulation functions whereas stringi provides a comprehensive set covering almost anything and everything.

**3. readr**


* The readr package in R, part of the tidyverse, is designed to simplify and streamline the process of reading and importing structured text data. Its philosophy centers around consistency, simplicity, and efficiency. By adhering to these principles, readr aims to provide a user-friendly experience for handling data.One of the key features is the consistent and straightforward interface across its functions. This uniformity makes it easier for users to remember and apply the various functions within the package.


**4. ggplot2**


* ggplot2 in R is a versatile data visualization package that operates on the grammar of graphics principles. Developed by Hadley Wickham, it simplifies the creation of complex visualizations by breaking down graphics into fundamental components. The layered approach allows users to build up plots by adding components incrementally. Aesthetic mappings play a crucial role, defining how variables are represented visually. For instance, one can map data variables to plot aesthetics such as color, size, or shape. With a rich set of geoms (geometric objects) and statistical transformations, ggplot2 facilitates the creation of diverse and informative visualizations. Its theming system provides flexibility for customization, enabling users to adapt the appearance of plots to their specific needs.

**5. tseries**


*  The lubridate package in R is a powerful and user-friendly library for handling date and time data. It simplifies the often complex and error-prone process of working with dates by providing intuitive functions that facilitate parsing, manipulation, and formatting of date-time objects. Developed by Hadley Wickham, lubridate builds on R's base date and time functions, offering a consistent and convenient interface for tasks such as extracting components (e.g., year, month, day), arithmetic operations, and handling time zones. One of its key features is the ability to handle both date and time information seamlessly, making it well-suited for various data analysis and visualization tasks where accurate temporal information is crucial. The package has gained popularity in the R community for its simplicity, versatility, and efficiency in handling temporal data, making it an essential tool for users working with time series, financial data, and other applications involving dates and times.



**Install 2 Libraries in R**

In [ ]:
install.packages("dplyr")
# Create a data frame with missing data
d <- data.frame(name = c("Abhi", "Bhavesh", "Chaman", "Dimri"),
				age = c(7, 5, 9, 16),
				ht = c(46, NA, NA, 69),
				school = c("yes", "yes", "no", "no"))

paste("Code1:")
# Display the data frame
print(d)
cat("\n")

paste("Code2:")
# Finding rows with NA value
rows_with_na <- d %>% filter(is.na(ht))
print(rows_with_na)
cat("\n")

paste("Code3:")
# Finding rows with no NA value
rows_without_na <- d %>% filter(!is.na(ht))
print(rows_without_na)


[1] "Code1:"

     name age ht school
1    Abhi   7 46    yes
2 Bhavesh   5 NA    yes
3  Chaman   9 NA     no
4   Dimri  16 69     no



[1] "Code2:"

     name age ht school
1 Bhavesh   5 NA    yes
2  Chaman   9 NA     no



[1] "Code3:"

   name age ht school
1  Abhi   7 46    yes
2 Dimri  16 69     no


In [ ]:
install.packages("stringr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
library(stringr)


[1] 3

In [ ]:
x <- c("adebcf", "gfhijk")
str_length(x)
str_sub(x, 3, 3)
str_sub(x, 2, -2)
str_to_upper(x)
str_order(x)
str_sort(x)

[1] 6 6

[1] "e" "h"

[1] "debc" "fhij"

[1] "ADEBCF" "GFHIJK"

[1] 1 2

[1] "adebcf" "gfhijk"

In [ ]:
install.packages("ggplot2")
install.packages("readr")
install.packages("tseries")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘xts’, ‘TTR’, ‘quadprog’, ‘zoo’, ‘quantmod’


